ALTER TABLE products ADD COLUMN tier INTEGER;
ALTER TABLE products ADD COLUMN code_count INTEGER;
ALTER TABLE products ADD COLUMN multi_date INTEGER;
UPDATE products SET tier=3, code_count=3, multi_date=NULL WHERE slug='be-live';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='brizy-design-kit';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='burner-mail';
UPDATE products SET tier=3, code_count=1, multi_date=NULL WHERE slug='coming-soon-maintenance-mode';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='crello';
UPDATE products SET tier=2, code_count=1, multi_date=NULL WHERE slug='cromojo';
UPDATE products SET tier=5, code_count=5, multi_date=1 WHERE slug='depositphotos';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='divmagic';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='docpro';
UPDATE products SET tier=3, code_count=1, multi_date=NULL WHERE slug='emailit';
UPDATE products SET tier=4, code_count=4, multi_date=1 WHERE slug='frontly';
UPDATE products SET tier=3, code_count=3, multi_date=NULL WHERE slug='getscreen-me';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='google-maps-scraper';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='google-maps-widget';
UPDATE products SET tier=2, code_count=2, multi_date=NULL WHERE slug='hoverify';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='itubego';
UPDATE products SET tier=3, code_count=3, multi_date=NULL WHERE slug='jivochat';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='keyword-hero';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='kingsumo';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='lumen5';
UPDATE products SET tier=2, code_count=2, multi_date=NULL WHERE slug='mailpoet';
UPDATE products SET tier=4, code_count=4, multi_date=1 WHERE slug='neuronwriter';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='pixlr';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='screentovideo';
UPDATE products SET tier=2, code_count=1, multi_date=NULL WHERE slug='semdash';
UPDATE products SET tier=5, code_count=5, multi_date=NULL WHERE slug='shortpixel';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='ticket-tailor';
UPDATE products SET tier=2, code_count=1, multi_date=NULL WHERE slug='voicedash';
UPDATE products SET tier=3, code_count=1, multi_date=NULL WHERE slug='wp-courseware';
UPDATE products SET tier=1, code_count=1, multi_date=NULL WHERE slug='yay-images';
